"""
Subgraph Query API — /api/query/*

Lets users explore the committed unified knowledge graph by:
  1. Selecting a database (neo4j | metta)
  2. Searching for entities by type and name/ID
  3. Discovering which relations and targets exist for a given entity
  4. Executing a subgraph query and getting back vis.js-ready graph data
"""
import sqlite3
import json
import os
from pathlib import Path
from fastapi import APIRouter, Query
from fastapi.responses import JSONResponse

router = APIRouter(prefix="/api/query", tags=["query"])

_ROOT = Path(__file__).parent.parent.parent

_DB_PATHS = {
    "neo4j": _ROOT / "data" / "triple_store_neo4j.db",
    "metta":  _ROOT / "data" / "triple_store_metta.db",
}


def _get_conn(db: str):
    path = _DB_PATHS.get(db)
    if not path or not path.exists():
        return None
    conn = sqlite3.connect(str(path))
    conn.row_factory = sqlite3.Row
    return conn


@router.get("/latest-compare")
async def latest_compare(fmt: str = "neo4j"):
    """Return path to the most recent compare_{fmt}.html across all run folders."""
    import glob as _glob
    pattern = str(_ROOT / "data" / "kg_output" / "*" / f"compare_{fmt}.html")
    files = sorted(_glob.glob(pattern), key=lambda f: Path(f).stat().st_mtime, reverse=True)
    if files:
        # Return relative path from project root
        rel = str(Path(files[0]).relative_to(_ROOT))
        return JSONResponse({"path": rel})
    return JSONResponse({"path": None})


# ── Subgraph HTML (same render as paper graph) ────────────────────────────────

@router.get("/subgraph-html")
async def subgraph_html(
    db:       str = Query("neo4j"),
    entity1:  str = Query(""),
    relation: str = Query(""),
    entity2:  str = Query(""),
    limit:    int = Query(80),
):
    """
    Run the same subgraph query but return a full HTML file generated by
    visualize_graph.render_html() — identical to the paper graph HTML.
    """
    import tempfile as _tmp
    import sys as _sys
    _sys.path.insert(0, str(_ROOT))

    conn = _get_conn(db)
    if not conn:
        from fastapi.responses import HTMLResponse
        return HTMLResponse("<h3>Database not found</h3>", status_code=404)

    try:
        conditions, params = [], []
        if entity1:
            conditions.append("(subject_name=? OR subject_id=? OR object_name=? OR object_id=?)")
            params += [entity1]*4
        if entity2:
            conditions.append("(subject_name=? OR subject_id=? OR object_name=? OR object_id=?)")
            params += [entity2]*4
        if relation:
            conditions.append("relation=?")
            params.append(relation)
        where = "WHERE " + " AND ".join(conditions) if conditions else ""
        params.append(limit)
        rows = conn.execute(
            f"SELECT * FROM triples {where} ORDER BY confidence DESC LIMIT ?", params
        ).fetchall()
    finally:
        conn.close()

    if not rows:
        from fastapi.responses import HTMLResponse
        return HTMLResponse(
            "<html><body style='background:#0d1117;color:#8b949e;font-family:Inter,sans-serif;"
            "display:flex;align-items:center;justify-content:center;height:100vh;font-size:14px'>"
            "<div style='text-align:center'><div style='font-size:32px;opacity:.3;margin-bottom:12px'>🔍</div>"
            "No results found for this query.</div></body></html>"
        )

    # Build confidence_channels lookup from all layer7_processed.json checkpoints
    # key: (subject_name, relation, object_name) → confidence_channels dict
    _ch_lookup: dict = {}
    try:
        ckpt_root = _ROOT / "data" / "checkpoints"
        if ckpt_root.exists():
            for ckpt_file in ckpt_root.rglob("layer7_processed.json"):
                try:
                    records = json.loads(ckpt_file.read_text(encoding="utf-8"))
                    for rec in records:
                        key = (rec.get("subject_name",""), rec.get("relation",""), rec.get("object_name",""))
                        ch = rec.get("confidence_channels")
                        if ch and isinstance(ch, dict):
                            _ch_lookup[key] = ch
                except Exception:
                    pass
    except Exception:
        pass

    # Convert rows → nodes/edges dicts compatible with visualize_graph.render_html
    nodes: dict = {}
    edges: list = []

    for i, r in enumerate(rows):
        rd = dict(r)
        for nid, nname, ntype in [
            (rd["subject_id"], rd["subject_name"], rd["subject_type"]),
            (rd["object_id"],  rd["object_name"],  rd["object_type"]),
        ]:
            if nid not in nodes:
                # render_html() expects {id: {entity_type, name, ...}} format
                nodes[nid] = {
                    "id":          nid,
                    "name":        nname or nid,
                    "entity_type": ntype or "OTHER",
                }
        try:
            src_papers = json.loads(rd.get("source_papers") or "[]")
        except Exception:
            src_papers = []

        src_paper_str = json.dumps(src_papers) if src_papers else ""
        # Look up actual computed confidence channels from checkpoint
        _ch_key = (rd["subject_name"], rd["relation"], rd["object_name"])
        _channels = _ch_lookup.get(_ch_key, {})
        edges.append({
            "id":            i,
            "source_id":     rd["subject_id"],
            "source_name":   rd["subject_name"],
            "target_id":     rd["object_id"],
            "target_name":   rd["object_name"],
            "relation":      rd["relation"],
            "confidence":    float(rd.get("confidence") or 0),
            "negated":       bool(rd.get("negated")),
            "source_paper":  src_papers[0] if src_papers else "",
            "source_papers": src_paper_str,
            "section":       rd.get("section") or "",
            "species":       rd.get("species") or "",
            "tissue":        rd.get("tissue") or "",
            "condition":     rd.get("condition") or "",
            "effect_size":   rd.get("effect_size") or "",
            "reasoning":          rd.get("reasoning") or "",
            "validation":         rd.get("validation_verdict") or "",
            "review_reason":      rd.get("review_reason") or "",
            "confidence_channels": json.dumps(_channels) if _channels else "{}",
            "_conf_channels":      _channels,
        })

    title = f"Query: {entity1 or ''}{'→'+relation if relation else ''}{'→'+entity2 if entity2 else ''} ({db.upper()})"

    # Write temp HTML using the existing render_html function
    try:
        from tools.visualize_graph import render_html
        import tempfile as _tmp
        with _tmp.NamedTemporaryFile(suffix=".html", delete=False, mode="w") as f:
            tmp_path = Path(f.name)
        render_html(nodes, edges, tmp_path, title=title, fast_physics=True)
        html = tmp_path.read_text(encoding="utf-8")
        tmp_path.unlink(missing_ok=True)
        from fastapi.responses import HTMLResponse
        return HTMLResponse(html)
    except Exception as exc:
        from fastapi.responses import HTMLResponse
        return HTMLResponse(f"<h3>Render error: {exc}</h3>", status_code=500)

# ── Entity types available in a database ─────────────────────────────────────

@router.get("/entity-types")
async def entity_types(db: str = Query("neo4j")):
    """Return all distinct entity types present in the database."""
    conn = _get_conn(db)
    if not conn:
        return JSONResponse({"types": []})
    try:
        rows = conn.execute(
            "SELECT DISTINCT subject_type as t FROM triples WHERE subject_type != '' "
            "UNION SELECT DISTINCT object_type FROM triples WHERE object_type != '' "
            "ORDER BY t"
        ).fetchall()
        return JSONResponse({"types": [r["t"] for r in rows]})
    finally:
        conn.close()


# ── Entity autocomplete ───────────────────────────────────────────────────────

@router.get("/entities")
async def entities(
    db:    str = Query("neo4j"),
    q:     str = Query(""),
    type_: str = Query("", alias="type"),
    limit: int = Query(15),
):
    """
    Autocomplete entity search.
    Returns [{id, name, type}] sorted by how many relations the entity has.
    """
    conn = _get_conn(db)
    if not conn:
        return JSONResponse({"entities": []})
    try:
        q_norm = q.replace("‘", "’").replace("’", "’")
        like = f"%{q_norm}%"
        subj_type_clause = "AND subject_type = ?" if type_ else ""
        obj_type_clause  = "AND object_type = ?"  if type_ else ""
        params = [like, like] + ([type_] if type_ else []) + \
                 [like, like] + ([type_] if type_ else []) + [limit]
        rows = conn.execute(f"""
            SELECT subject_id as id, subject_name as name, subject_type as type,
                   COUNT(*) as cnt
            FROM triples
            WHERE (subject_name LIKE ? OR subject_id LIKE ?)
            {subj_type_clause}
            GROUP BY subject_id, subject_name, subject_type
            UNION
            SELECT object_id as id, object_name as name, object_type as type,
                   COUNT(*) as cnt
            FROM triples
            WHERE (object_name LIKE ? OR object_id LIKE ?)
            {obj_type_clause}
            GROUP BY object_id, object_name, object_type
            ORDER BY cnt DESC
            LIMIT ?
        """, params).fetchall()
        seen, result = set(), []
        for r in rows:
            key = (r["id"], r["name"])
            if key not in seen:
                seen.add(key)
                result.append({"id": r["id"], "name": r["name"], "type": r["type"]})
        return JSONResponse({"entities": result})
    finally:
        conn.close()


# ── Relations available for a given entity ───────────────────────────────────

@router.get("/relations")
async def relations(
    db:     str = Query("neo4j"),
    entity: str = Query(""),   # entity name or ID
):
    """
    Return distinct relation types that exist for a given entity (as subject OR object).
    Also returns direction: 'outgoing' | 'incoming' | 'both'.
    """
    conn = _get_conn(db)
    if not conn:
        return JSONResponse({"relations": []})
    try:
        out_rows = conn.execute(
            "SELECT DISTINCT relation FROM triples "
            "WHERE subject_name = ? OR subject_id = ?",
            (entity, entity)
        ).fetchall()
        in_rows = conn.execute(
            "SELECT DISTINCT relation FROM triples "
            "WHERE object_name = ? OR object_id = ?",
            (entity, entity)
        ).fetchall()
        out_rels = {r["relation"] for r in out_rows}
        in_rels  = {r["relation"] for r in in_rows}
        all_rels = out_rels | in_rels
        result = []
        for rel in sorted(all_rels):
            if rel in out_rels and rel in in_rels:
                direction = "both"
            elif rel in out_rels:
                direction = "outgoing"
            else:
                direction = "incoming"
            result.append({"relation": rel, "direction": direction})
        return JSONResponse({"relations": result})
    finally:
        conn.close()


# ── Available connections for an entity type ─────────────────────────────────

@router.get("/type-connections")
async def type_connections(
    db:          str = Query("neo4j"),
    entity_type: str = Query(""),  # e.g. GENE
):
    """
    Return available relation→target_type pairs for a given entity type.
    Shows what connections are possible from this entity type in the KG.
    e.g. GENE → [{'relation':'binds_to','target_type':'PROTEIN','direction':'outgoing','count':5}, ...]
    """
    conn = _get_conn(db)
    if not conn:
        return JSONResponse({"connections": []})
    try:
        rows = conn.execute("""
            SELECT relation, object_type as target_type, COUNT(*) as cnt, 'outgoing' as dir
            FROM triples
            WHERE subject_type = ?
            GROUP BY relation, object_type
            UNION
            SELECT relation, subject_type as target_type, COUNT(*) as cnt, 'incoming' as dir
            FROM triples
            WHERE object_type = ?
            GROUP BY relation, subject_type
            ORDER BY cnt DESC
        """, (entity_type, entity_type)).fetchall()
        result = [{"relation": r["relation"], "target_type": r["target_type"],
                   "direction": r["dir"], "count": r["cnt"]} for r in rows]
        return JSONResponse({"connections": result})
    finally:
        conn.close()


# ── Connected targets for entity + relation ───────────────────────────────────

@router.get("/targets")
async def targets(
    db:       str = Query("neo4j"),
    entity:   str = Query(""),
    relation: str = Query(""),   # empty = any relation
    limit:    int = Query(20),
):
    """
    Return entities connected to the given entity (optionally via a specific relation).
    """
    conn = _get_conn(db)
    if not conn:
        return JSONResponse({"targets": []})
    try:
        rel_filter = "AND relation = ?" if relation else ""
        params_out = [entity, entity] + ([relation] if relation else []) + [limit]
        params_in  = [entity, entity] + ([relation] if relation else []) + [limit]

        out_rows = conn.execute(f"""
            SELECT object_id as id, object_name as name, object_type as type,
                   relation, confidence, 'outgoing' as direction
            FROM triples
            WHERE (subject_name = ? OR subject_id = ?)
            {rel_filter}
            ORDER BY confidence DESC LIMIT ?
        """, params_out).fetchall()

        in_rows = conn.execute(f"""
            SELECT subject_id as id, subject_name as name, subject_type as type,
                   relation, confidence, 'incoming' as direction
            FROM triples
            WHERE (object_name = ? OR object_id = ?)
            {rel_filter}
            ORDER BY confidence DESC LIMIT ?
        """, params_in).fetchall()

        seen, result = set(), []
        for r in list(out_rows) + list(in_rows):
            key = (r["id"], r["name"])
            if key not in seen:
                seen.add(key)
                result.append({
                    "id": r["id"], "name": r["name"], "type": r["type"],
                    "relation": r["relation"], "confidence": r["confidence"],
                    "direction": r["direction"],
                })
        result.sort(key=lambda x: x["confidence"], reverse=True)
        return JSONResponse({"targets": result[:limit]})
    finally:
        conn.close()


# ── Subgraph query ────────────────────────────────────────────────────────────

@router.get("/subgraph")
async def subgraph(
    db:           str = Query("neo4j"),
    entity1:      str = Query(""),
    type1:        str = Query(""),
    relation:     str = Query(""),
    entity2:      str = Query(""),
    type2:        str = Query(""),
    entity_extra: list = Query([]),  # additional entities for N-node queries
    limit:        int = Query(150),
):
    """
    Return a vis.js-compatible subgraph matching the query.
    entity1 and/or entity2 can be name or ID.
    relation can be empty (wildcard).
    """
    conn = _get_conn(db)
    if not conn:
        return JSONResponse({"nodes": [], "edges": [], "count": 0})
    try:
        conditions = []
        params: list = []

        if entity1:
            if type1:
                conditions.append(
                    "((subject_name=? OR subject_id=?) AND subject_type=? "
                    "OR (object_name=? OR object_id=?) AND object_type=?)"
                )
                params += [entity1, entity1, type1, entity1, entity1, type1]
            else:
                conditions.append(
                    "(subject_name=? OR subject_id=? OR object_name=? OR object_id=?)"
                )
                params += [entity1, entity1, entity1, entity1]

        if entity2:
            conditions.append(
                "(subject_name = ? OR subject_id = ? OR object_name = ? OR object_id = ?)"
            )
            params += [entity2, entity2, entity2, entity2]

        # Extra entities (N-node queries) — each must appear in at least one triple
        for extra in entity_extra:
            if extra:
                conditions.append(
                    "(subject_name=? OR subject_id=? OR object_name=? OR object_id=?)"
                )
                params += [extra, extra, extra, extra]

        if relation:
            conditions.append("relation = ?")
            params.append(relation)

        where = "WHERE " + " AND ".join(conditions) if conditions else ""
        params.append(limit)

        rows = conn.execute(
            f"SELECT * FROM triples {where} ORDER BY confidence DESC LIMIT ?",
            params
        ).fetchall()

        # Build vis.js nodes + edges
        nodes: dict = {}
        edges: list = []

        _TYPE_COLORS = {
            "GENE": "#58A6FF", "PROTEIN": "#3FB950", "DISEASE": "#FF7B72",
            "DRUG": "#D2A8FF", "PATHWAY": "#FFA657", "CELL_TYPE": "#79C0FF",
            "GENOMIC_VARIANT": "#F0883E", "CHEMICAL": "#A5D6FF",
            "BIOLOGICAL_PROCESS": "#56D364", "PHENOTYPE": "#FF9A9A",
        }

        for i, r in enumerate(rows):
            for nid, nname, ntype in [
                (r["subject_id"], r["subject_name"], r["subject_type"]),
                (r["object_id"],  r["object_name"],  r["object_type"]),
            ]:
                if nid not in nodes:
                    color = _TYPE_COLORS.get(ntype, "#8B949E")
                    nodes[nid] = {
                        "id":    nid,
                        "label": nname or nid,
                        "title": f"{ntype}: {nname or nid}",
                        "color": {"background": color, "border": color,
                                  "highlight": {"background": "#FFFFFF", "border": color}},
                        "font":  {"color": "#FFFFFF", "size": 13},
                        "shape": "dot", "size": 18,
                        "_type": ntype,
                    }

            try:
                src_papers = json.loads(r["source_papers"] or "[]")
            except Exception:
                src_papers = []

            edges.append({
                "id":    f"e{i}",
                "from":  r["subject_id"],
                "to":    r["object_id"],
                "label": r["relation"].replace("_", " "),
                "title": f"{r['relation']} (conf: {r['confidence']:.2f})",
                "color": {"color": "#F59E0B" if r["flagged_for_review"] else "#58A6FF"},
                "width": max(1.5, float(r["confidence"] or 0) * 3),
                "arrows": {"to": {"enabled": True, "scaleFactor": 0.6}},
                "dashes": bool(r["negated"]),
                "_relation":   r["relation"],
                "_confidence": r["confidence"],
                "_source_papers": src_papers,
                "_reasoning":  r["reasoning"] or "",
            })

        return JSONResponse({
            "nodes": list(nodes.values()),
            "edges": edges,
            "count": len(rows),
            "db":    db,
        })
    finally:
        conn.close()
